"""Provider-agnostic chat client.

Issues a standard OpenAI-compatible ``POST {LLM_BASE_URL}/chat/completions``,
which Azure OpenAI and the common McKinsey gateway variants all accept. The
endpoint is supplied entirely through environment variables, so pointing this
at whichever gateway is approved for the engagement is a configuration change
rather than a code change.

Nothing in this module lets the API key reach a caller, a log line or a
traceback: upstream text is scrubbed before it is logged, upstream exceptions
are never chained (their request objects carry the auth headers), and no
message raised from here is passed through to the browser verbatim.
"""

import logging
import os

import httpx

log = logging.getLogger("nazir.llm")

# httpx logs every request URL at INFO. The base URL is operator-supplied and
# could carry a credential in its userinfo or query, so keep it out of the logs.
logging.getLogger("httpx").setLevel(logging.WARNING)

TEMPERATURE = 0.2
MAX_TOKENS = 900

# A minister is waiting on this in the browser: give up on an unreachable
# gateway quickly, but allow the model a full minute to answer.
TIMEOUT = httpx.Timeout(60.0, connect=10.0)


class LLMNotConfigured(RuntimeError):
    """Raised when no endpoint is configured and mock mode is off."""


class LLMUpstreamError(RuntimeError):
    """Raised when the endpoint is configured but returned no usable reply."""


def _env(name: str, default: str = "") -> str:
    return (os.getenv(name) or default).strip()


def is_mock() -> bool:
    return _env("LLM_MOCK", "0") == "1"


def _scrub(text: str, limit: int = 500) -> str:
    """Trim upstream text for a log line, with the API key removed."""
    key = _env("LLM_API_KEY")
    if key:
        text = text.replace(key, "***")
    return text[:limit]


def _mock_reply(messages: list[dict]) -> str:
    question = next(
        (m.get("content", "") for m in reversed(messages) if m.get("role") == "user"),
        "",
    )
    return (
        "**Mock mode.** No LLM endpoint is configured, so this is a canned reply "
        "used to exercise the chat interface.\n\n"
        f"You asked: {question}\n\n"
        "Once `LLM_BASE_URL`, `LLM_MODEL` and `LLM_API_KEY` are set, this answer "
        "will be generated by the model, grounded in the indicators and use-case "
        "data this panel sends with every turn."
    )


async def complete(messages: list[dict]) -> tuple[str, str]:
    """Return ``(reply_text, model_name)``.

    Raises ``LLMNotConfigured`` when no endpoint is set, and
    ``LLMUpstreamError`` when one is set but did not yield a reply.
    """
    if is_mock():
        return _mock_reply(messages), "mock"

    base = _env("LLM_BASE_URL").rstrip("/")
    model = _env("LLM_MODEL")
    key = _env("LLM_API_KEY")

    if not (base and model and key):
        raise LLMNotConfigured(
            "LLM_BASE_URL, LLM_MODEL and LLM_API_KEY must all be set. "
            "Set LLM_MOCK=1 to exercise the interface without an endpoint."
        )

    params = {}
    version = _env("LLM_API_VERSION")
    if version:
        params["api-version"] = version

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {key}",
        # Azure OpenAI reads the key from this header instead of Authorization.
        "api-key": key,
    }
    payload = {
        "model": model,
        "messages": messages,
        "temperature": TEMPERATURE,
        "max_tokens": MAX_TOKENS,
    }

    try:
        async with httpx.AsyncClient(timeout=TIMEOUT) as client:
            response = await client.post(
                f"{base}/chat/completions", json=payload, headers=headers, params=params
            )
    except httpx.HTTPError as exc:
        # ``from None`` on purpose: the httpx exception holds the request, and
        # the request holds the auth headers. Do not chain it into a traceback.
        log.warning("chat call failed: %s: %s", type(exc).__name__, _scrub(str(exc)))
        raise LLMUpstreamError("upstream request failed") from None

    if response.status_code != 200:
        log.warning(
            "chat endpoint returned %s: %s", response.status_code, _scrub(response.text)
        )
        raise LLMUpstreamError(f"upstream returned {response.status_code}")

    try:
        data = response.json()
    except ValueError:
        log.warning("chat endpoint returned a body that is not JSON")
        raise LLMUpstreamError("upstream response was not JSON") from None

    # Some gateways report a refusal or a quota problem in a 200 body.
    if isinstance(data, dict) and data.get("error"):
        log.warning("chat endpoint reported an error: %s", _scrub(str(data["error"])))
        raise LLMUpstreamError("upstream reported an error")

    try:
        reply = data["choices"][0]["message"]["content"]
    except (KeyError, IndexError, TypeError):
        log.warning("chat endpoint returned no completion: %s", _scrub(str(data)))
        raise LLMUpstreamError("upstream response carried no completion") from None

    if not isinstance(reply, str) or not reply.strip():
        raise LLMUpstreamError("upstream returned an empty completion")

    return reply, str(data.get("model") or model)
